# Site settings
title: Web-CAT
description: >
  Automatic grading using student-written tests with the most widely used
  open-source automatic program grader in the world.
url: "https://web-cat.org"
repository: web-cat/web-cat.github.io
repository_tree: master
lang: en


permalink: none
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - package.json
  - package-lock.json
  - /node_modules
  - /utterances.json

collections:
  projects:
    output: true


# ----------------------------------------------------------------------
# Front matter defaults:
# ----------------------------------------------------------------------
defaults:
  - scope:
      path: ""
    values:
      layout: article
      license: true
      sidebar:
        nav: sb-main
      show_edit_on_github: true
      full_width: true
  - scope:
      type: posts
    values:
      license: false
      show_edit_on_github: false
      permalink: /:categories/:year/:month/:day/:title:output_ext
  - scope:
      type: projects
    values:
      layout: project
      permalink: /:collection/:title/
      show_date: false
      show_tags: false


# ----------------------------------------------------------------------
# Theme selection:
# ----------------------------------------------------------------------
# remote_theme: pmarsceill/just-the-docs
remote_theme: kitian616/jekyll-TeXt-theme


# ----------------------------------------------------------------------
# For JTD theme:
# ----------------------------------------------------------------------
# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "Web-CAT on GitHub":
    - "//github.com/web-cat"

# Color scheme currently only supports "dark" or nil (default)

color_scheme: nil

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
#ga_tracking: UA-2709176-10


# ----------------------------------------------------------------------
# For TeXT theme:
# ----------------------------------------------------------------------
text_skin: default
highlight_theme: default
license: LGPL-3.0
search:
  provider: default

author:
  type      : organization
  name      : Virginia Tech
  url       : http://www.cs.vt.edu/
  bio: >
    Web-CAT and related projects are academic research projects developed
    at Virginia Tech. The project lead is Stephen Edwards.
  email     : webcat@vt.edu
  facebook  :
  twitter   : 
  linkedin  :
  github    : web-cat

# For addtional options:
# https://raw.githubusercontent.com/kitian616/jekyll-TeXt-theme/master/_config.yml
